# Generated by Django 5.0.2 on 2024-04-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('payment_option', models.CharField(choices=[('bkash', 'Bkash'), ('rocket', 'Rocket'), ('mastercard', 'Mastercard')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('num_rooms', models.IntegerField()),
                ('cvv', models.CharField(max_length=3)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=15, null=True)),
                ('room_type', models.CharField(choices=[('NAC', 'Non AC'), ('YAC', 'AC'), ('DEL', 'Deluxe'), ('KIN', 'King'), ('QUE', 'Queen')], max_length=5)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
            ],
        ),
    ]
