# Generated by Django 5.0.2 on 2024-04-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymenthandle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
